# Introduction

The fundamental problem of asset pricing is in understanding
the risk premium through an asset pricing kernel.
The challenges in estimating the asset-pricing kernel come
in three aspects.

Firstly, in choosing the right factors (data features) to
estimate the pricing kernel.
Current approaches involve Fama French 5-factor model (Fama
& French, 2015) or machine learning LASSO approach in Taming
the Factor Zoo (Feng et al., 2020).

Secondly, in estimating the functional form of the pricing
kernel.
Fama French assumes linear pricing kernel, while others
papers explored non-linear models using machine learning
techniques such as ensemble and boosting tree models, feed
forward neural network.  With machine learning techniques
providing more significant economic gains (Gu et al., 2018).

Lastly, in choosing the right portfolio (combination of
individual assets) to estimate the pricing kernel.
Current approaches follow the characteristics sorted
portfolio, such as Fama French size, book-to-market,
operating profitability and investment portfolio.

A recent paper proposed a Generative Adversarial Network
(GAN) model that attempts to solve all three problems in a
single setup (Chen et al., 2019).
GAN models consist of a discriminative neural network model
and a generative neural network model. The discriminative
and generative works like police and thief with contrasting
objectives linked with a single pricing error loss function.
The competition can be viewed as a zero-sum game with the
discriminative network attempts to model the pricing
kernel, improving the asset pricing model's explanatory
power and reducing the pricing error loss. And the
generative network attempts to choose portfolio and factors
that is least explained by the asset pricing model to
increase the pricing error loss.
The goal is to build a discriminative network model with the
best pricing kernel estimation and a generative network
model with the best portfolio and factor construction.

The paper further includes macroeconomic data using neural
network long short-term memory (LSTM) proposed commonly used in
predictions with a time series structure.

Our contribution comes in three levels.
Firstly, we attempt to validate Chen's research using the
network model proposed and data provided in the paper.
Secondly, the current code base released by Chen relies on 
TensorFlow v1.0, a software library that has been depreciated.
We upgrade the existing code base using TensorFlow v2.0,
the latest version of the software library.
Furthermore, we attempt to provide an easy-to-use
open-source software package that will be widely available
to all researchers interesting in applying the GAN model to
any asset class and data of interest.
Lastly, we illustrate the use case of our software package
and testify the model performance in a different country. 
