---
output:
    bookdown::pdf_document2:
        # template: ./template/svm-latex-ms.tex
        fig_caption: yes
        keep_tex: no
        number_sections: yes
        toc: true
        toc_depth: 3
        latex_engine: pdflatex
title:
    "Generative Adversarial Network (GAN) model in Asset Pricing"
author:
    "Wang Lingjie"
    # name: "Wang Lingjie"
    # affiliation: "National University of Singapore"
header-includes:
    - \usepackage{setspace}\doublespacing
date: "`r format(Sys.time(), '%B %d, %Y')`"
keywords:
    "Generative Adversarial Network,
    Asset Pricing
    "
thanks: "Replication files are available on the author's
        [Github account](https://github.com/lingjie00/asset_pricing)"
geometry: margin=2.5cm
urlcolor: blue
# fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: ref.bib
nocite: "@fama_five-factor_2015 @fama_choosing_2017 @coulombe_can_2021"
csl: ./template/apa.csl
abstract: 
    "
    The critical goal in asset pricing is to understand the
    differences in asset’s average returns. No-arbitrage
    pricing theory provides a direct explanation by
    explaining price differences through an asset-pricing
    kernel. However, it remains a challenge to estimate the
    asset-pricing kernel. The difficulties include (1)
    choosing the right factors, (2) estimating the pricing
    kernel’s functional form, and (3) selecting the right
    portfolio to estimate the kernel. A recent paper
    proposed a Generative Adversarial Network (GAN) model
    that attempts to solve all three challenges in a single
    setup and claim to achieve the best performance compared
    to all existing models [@chen_deep_2019]. This paper empirically
    validated Chen et al. (2019)’s research which is based on the United
    States stock data with the United Kingdom (UK) London
    Stock Exchange 2011 - 2021 data.
    "
---

<!-- Results
We found the model performance to be
consistent in the UK 2011 - 2021 data,
outperforming Fama French model in explaining
the asset mispricing. -->

<!-- main markdown for the whole thesis 
useful link: http://svmiller.com/blog/2016/02/svm-r-markdown-manuscript/
-->

```{r echo=F}
# libraries
```

<!-- introduction -->

```{r, child=("introduction.Rmd")}
```

<!-- literature review -->

```{r, child=("lit_review.Rmd")}
```

<!-- model -->

```{r, child=("model.Rmd")}
```

<!-- model training -->
```{r, child=("training.Rmd")}
```

<!-- model evaluation -->
```{r, child=("metrics.Rmd")}
```

<!-- empirical results -->

```{r, child=("results.Rmd")}
```

<!-- conclusion -->

```{r, child=("conclusion.Rmd")}
```

<!--list of tables and figures-->
# List of Tables and Figures

\listoffigures

\listoftables

<!-- reference -->

# Reference
